name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: jekyll-deploy
      uses: DavidS/jekyll-deploy@1.0.0

